[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = ">=3.9,<3.13"
seaborn = "*"
seaborn-analyzer = "0.3.5"
